"""Generate frontend/src/lib/api/catalog-meta.ts from catalog models.

Iterates ``CatalogModel`` subclasses to produce a TypeScript file with:
- ENTITY_TYPES: canonical hyphenated public entity_type values + labels
- MEDIA_CATEGORIES: per-entity media category lists, keyed by entity_type

Run via ``make api-gen`` or directly::

    python manage.py export_catalog_meta
"""

from __future__ import annotations

from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.core.models import CatalogModel


class Command(BaseCommand):
    help = "Generate frontend/src/lib/api/catalog-meta.ts from catalog models."

    def handle(self, **options):
        entity_types: list[tuple[str, str]] = []
        media_categories: dict[str, list[str]] = {}

        for cls in _iter_concrete_subclasses(CatalogModel):
            if not hasattr(cls, "link_url_pattern"):
                continue
            key = cls.entity_type
            entity_types.append((key, cls._meta.verbose_name.title()))
            cats = getattr(cls, "MEDIA_CATEGORIES", [])
            if cats:
                media_categories[key] = list(cats)

        entity_types.sort()

        lines = [
            "// Generated by: python manage.py export_catalog_meta",
            "// Do not edit manually.",
            "",
            "export const ENTITY_TYPES = [",
        ]
        for value, label in entity_types:
            lines.append(f"  {{ value: '{value}', label: '{label}' }},")
        lines.append("] as const;")
        lines.append("")
        lines.append(
            "export type EntityTypeValue = (typeof ENTITY_TYPES)[number]['value'];"
        )
        lines.append("")
        lines.append("export const MEDIA_CATEGORIES = {")
        for key, cats in sorted(media_categories.items()):
            cats_str = ", ".join(f"'{c}'" for c in cats)
            lines.append(f"  '{key}': [{cats_str}],")
        lines.append("} as const;")
        lines.append("")

        output_path = (
            Path(settings.BASE_DIR).parent / "frontend/src/lib/api/catalog-meta.ts"
        )
        output_path.write_text("\n".join(lines))
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))


def _iter_concrete_subclasses(root):
    for cls in root.__subclasses__():
        yield from _iter_concrete_subclasses(cls)
        meta = getattr(cls, "_meta", None)
        if meta is None or meta.abstract:
            continue
        yield cls
