// Generated by: python manage.py export_catalog_meta
// Do not edit manually.

export const ENTITY_TYPES = [
	{ value: 'cabinet', label: 'Cabinet' },
	{ value: 'corporate-entity', label: 'Corporate Entity' },
	{ value: 'credit-role', label: 'Credit Role' },
	{ value: 'display-subtype', label: 'Display Subtype' },
	{ value: 'display-type', label: 'Display Type' },
	{ value: 'franchise', label: 'Franchise' },
	{ value: 'game-format', label: 'Game Format' },
	{ value: 'gameplay-feature', label: 'Gameplay Feature' },
	{ value: 'manufacturer', label: 'Manufacturer' },
	{ value: 'model', label: 'Model' },
	{ value: 'person', label: 'Person' },
	{ value: 'reward-type', label: 'Reward Type' },
	{ value: 'series', label: 'Series' },
	{ value: 'system', label: 'System' },
	{ value: 'tag', label: 'Tag' },
	{ value: 'technology-generation', label: 'Technology Generation' },
	{ value: 'technology-subgeneration', label: 'Technology Subgeneration' },
	{ value: 'theme', label: 'Theme' },
	{ value: 'title', label: 'Title' }
] as const;

export type EntityTypeValue = (typeof ENTITY_TYPES)[number]['value'];

export const MEDIA_CATEGORIES = {
	'gameplay-feature': ['other'],
	manufacturer: ['logo', 'other'],
	model: ['backglass', 'playfield', 'cabinet', 'other'],
	person: ['portrait', 'other']
} as const;
