# Generated by Django 6.0.2 on 2026-02-23 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("provenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="claim",
            name="provenance_unique_active_claim_per_source_field",
        ),
        migrations.RemoveConstraint(
            model_name="claim",
            name="provenance_unique_active_claim_per_user_field",
        ),
        migrations.AddField(
            model_name="claim",
            name="claim_key",
            field=models.CharField(
                default="",
                help_text='Identity key for uniqueness. Equals field_name for scalar claims. For relationship claims, encodes the relationship identity (e.g., "credit|person:pat-lawlor|role:art").',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="field_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["content_type", "object_id", "claim_key"],
                name="provenance__content_ae6aad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("source__isnull", False)),
                fields=("content_type", "object_id", "source", "claim_key"),
                name="provenance_unique_active_claim_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", False)),
                fields=("content_type", "object_id", "user", "claim_key"),
                name="provenance_unique_active_claim_per_user",
            ),
        ),
    ]
