# Generated by Django 6.0.3 on 2026-04-28 20:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_license_slug_lowercase_and_name_unique_ci'),
        ('provenance', '0002_changeset_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='provenance_source_slug_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='provenance_source_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='provenance_source_unique_name_ci'),
        ),
    ]
