# Generated by Django 6.0.3 on 2026-04-29 17:24

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('spdx_id', models.CharField(blank=True, help_text='Standard SPDX identifier (e.g., CC-BY-SA-4.0). Null for non-standard entries.', max_length=100, null=True, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, help_text='Link to canonical license deed.')),
                ('allows_display', models.BooleanField(default=False, help_text='Informational: does this license permit public display? Not used as a runtime gate.')),
                ('requires_attribution', models.BooleanField(default=False)),
                ('restricts_commercial', models.BooleanField(default=False)),
                ('allows_derivatives', models.BooleanField(default=True)),
                ('requires_share_alike', models.BooleanField(default=False)),
                ('permissiveness_rank', models.PositiveSmallIntegerField(default=0, help_text='Higher = more permissive. Used by the global display threshold.')),
            ],
            options={
                'ordering': ['-permissiveness_rank', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='core_license_name_not_blank'), models.CheckConstraint(condition=models.Q(('short_name', ''), _negated=True), name='core_license_short_name_not_blank'), models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='core_license_slug_not_blank'), models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='core_license_slug_lowercase'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='core_license_unique_name_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('short_name'), name='core_license_unique_short_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='RecordReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField()),
                ('target_id', models.PositiveBigIntegerField()),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_record_target__005216_idx'), models.Index(fields=['source_type', 'source_id'], name='core_record_source__a2e30f_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type', 'target_id'), name='core_recordreference_unique_source_target')],
            },
        ),
    ]
