# Generated by Django 6.0.3 on 2026-04-28 20:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='core_license_slug_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='core_license_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='core_license_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('short_name'), name='core_license_unique_short_name_ci'),
        ),
    ]
