# Generated by Django 6.0.3 on 2026-05-07 06:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="license",
            name="core_license_slug_lowercase",
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="core_license_slug_lowercase",
            ),
        ),
    ]
