name: Task
description: Work that doesnt involve committing to the repo
title: "Task"
labels: ["task"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What needs to be done?
      description: Describe the task or decision.
