# Generated by Django 6.0.2 on 2026-02-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text='Brand name if different (e.g., "Bally" for Midway Manufacturing)',
                        max_length=200,
                    ),
                ),
                (
                    "opdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="OPDB's manufacturer_id for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text="Wikidata QID, e.g. Q180268",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("dissolved_year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        help_text='Wikidata QID, e.g., "Q312897"',
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Wikidata ID",
                    ),
                ),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("birth_month", models.IntegerField(blank=True, null=True)),
                ("birth_day", models.IntegerField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("death_month", models.IntegerField(blank=True, null=True)),
                ("death_day", models.IntegerField(blank=True, null=True)),
                (
                    "birth_place",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opdb_id",
                    models.CharField(
                        help_text='OPDB group identifier, e.g., "G5pe4"',
                        max_length=50,
                        unique=True,
                        verbose_name="OPDB group ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text='Common abbreviation, e.g., "MM" for Medieval Madness',
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturerEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                        max_length=300,
                    ),
                ),
                (
                    "ipdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="IPDB's ManufacturerId for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "years_active",
                    models.CharField(
                        blank=True,
                        help_text='Operating period, e.g., "1931-1977"',
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "manufacturer entity",
                "verbose_name_plural": "manufacturer entities",
                "ordering": ["manufacturer", "years_active"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "titles",
                    models.ManyToManyField(
                        blank=True, related_name="series", to="catalog.title"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MachineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ipdb_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="IPDB ID"
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB ID",
                    ),
                ),
                (
                    "pinside_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Pinside ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "machine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "Pure Mechanical"),
                            ("EM", "Electromechanical"),
                            ("SS", "Solid State"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reels", "Score Reels"),
                            ("lights", "Backglass Lights"),
                            ("alpha", "Alpha-Numeric"),
                            ("dmd", "Dot Matrix Display"),
                            ("cga", "CGA (Color Graphics)"),
                            ("lcd", "LCD Screen"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "player_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("production_quantity", models.CharField(blank=True, max_length=100)),
                (
                    "flipper_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pinside_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("educational_text", models.TextField(blank=True)),
                ("sources_notes", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "alias_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent machine model if this is a cosmetic/LE variant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="catalog.manufacturer",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hardware system (resolved from system claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.system",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Resolved theme tags (materialized from relationship claims).",
                        related_name="machine_models",
                        to="catalog.theme",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        help_text="Title this machine belongs to (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="catalog.title",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("design", "Design"),
                            ("art", "Art"),
                            ("mechanics", "Mechanics"),
                            ("music", "Music"),
                            ("sound", "Sound"),
                            ("voice", "Voice"),
                            ("software", "Software"),
                            ("animation", "Dots/Animation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.machinemodel",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="catalog.person",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "person__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "person", "role"),
                        name="catalog_unique_credit_per_model_person_role",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["manufacturer", "year"], name="catalog_mac_manufac_3e73b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["machine_type", "year"], name="catalog_mac_machine_9c99fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["display_type"], name="catalog_mac_display_a86c1c_idx"
            ),
        ),
    ]
