# Generated by Django 6.0.2 on 2026-02-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="wikidata_id",
            field=models.CharField(
                blank=True,
                help_text='Wikidata QID, e.g., "Q312897"',
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Wikidata ID",
            ),
        ),
    ]
