# Generated by Django 6.0.3 on 2026-03-10 06:17

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=200)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.person",
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("value"),
                        name="catalog_unique_person_alias_lower",
                    )
                ],
            },
        ),
    ]
