# Generated by Django 6.0.3 on 2026-05-07 06:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cabinet",
            name="catalog_cabinet_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="corporateentity",
            name="catalog_corporateentity_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="creditrole",
            name="catalog_creditrole_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="displaysubtype",
            name="catalog_displaysubtype_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="displaytype",
            name="catalog_displaytype_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="franchise",
            name="catalog_franchise_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="gameformat",
            name="catalog_gameformat_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="gameplayfeature",
            name="catalog_gameplayfeature_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="catalog_location_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="catalog_location_location_path_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="machinemodel",
            name="catalog_machinemodel_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="manufacturer",
            name="catalog_manufacturer_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="person",
            name="catalog_person_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="rewardtype",
            name="catalog_rewardtype_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="series",
            name="catalog_series_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="system",
            name="catalog_system_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="tag",
            name="catalog_tag_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="technologygeneration",
            name="catalog_technologygeneration_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="technologysubgeneration",
            name="catalog_technologysubgeneration_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="theme",
            name="catalog_theme_slug_lowercase",
        ),
        migrations.RemoveConstraint(
            model_name="title",
            name="catalog_title_slug_lowercase",
        ),
        migrations.AddConstraint(
            model_name="cabinet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_cabinet_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="corporateentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_corporateentity_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_creditrole_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="displaysubtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_displaysubtype_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="displaytype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_displaytype_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="franchise",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_franchise_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameformat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_gameformat_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayfeature",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_gameplayfeature_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_location_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "location_path",
                        django.db.models.functions.text.Lower("location_path"),
                    )
                ),
                name="catalog_location_location_path_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_machinemodel_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_manufacturer_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_person_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_rewardtype_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_series_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="system",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_system_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_tag_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="technologygeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_technologygeneration_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="technologysubgeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_technologysubgeneration_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_theme_slug_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="title",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slug", django.db.models.functions.text.Lower("slug"))
                ),
                name="catalog_title_slug_lowercase",
            ),
        ),
    ]
