# Generated by Django 6.0.2 on 2026-03-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="corporateentity",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "name"),
                name="catalog_unique_corporate_entity_per_manufacturer",
            ),
        ),
    ]
