# Generated by Django 6.0.2 on 2026-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineTypeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("PM", "Pure Mechanical"),
                            ("EM", "Electromechanical"),
                            ("SS", "Solid State"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
