# Generated by Django 6.0.3 on 2026-04-21 15:48
#
# State-only migration: these ManyToManyField declarations use through=Credit,
# which already exists. No new tables or columns are created. Wrapping the
# AddField ops in SeparateDatabaseAndState prevents Django's SQLite backend
# from doing an unnecessary full-table rebuild; on Postgres these would be
# no-ops even without the wrapper.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_system_manufacturer"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="creditrole",
                    name="machine_models",
                    field=models.ManyToManyField(
                        related_name="+",
                        through="catalog.Credit",
                        through_fields=("role", "model"),
                        to="catalog.machinemodel",
                    ),
                ),
                migrations.AddField(
                    model_name="creditrole",
                    name="series_credited",
                    field=models.ManyToManyField(
                        related_name="+",
                        through="catalog.Credit",
                        through_fields=("role", "series"),
                        to="catalog.series",
                    ),
                ),
            ],
        ),
    ]
