# Generated by Django 6.0.2 on 2026-02-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_person_birth_day_person_birth_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designcredit",
            name="role",
            field=models.CharField(
                choices=[
                    ("concept", "Concept"),
                    ("design", "Design"),
                    ("art", "Art"),
                    ("mechanics", "Mechanics"),
                    ("music", "Music"),
                    ("sound", "Sound"),
                    ("voice", "Voice"),
                    ("software", "Software"),
                    ("animation", "Dots/Animation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
