# Generated by Django 6.0.2 on 2026-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_unique_corporate_entity_per_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinemodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classification tags (materialized from relationship claims).",
                related_name="machine_models",
                to="catalog.tag",
            ),
        ),
    ]
