# Generated by Django 6.0.2 on 2026-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_machinetypeprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayTypeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("reels", "Score Reels"),
                            ("lights", "Backglass Lights"),
                            ("alpha", "Alpha-Numeric"),
                            ("dmd", "Dot Matrix Display"),
                            ("cga", "CGA (Color Graphics)"),
                            ("lcd", "LCD Screen"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
