# Generated by Django 6.0.2 on 2026-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_designcredit_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="dissolved_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="founded_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="headquarters",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="wikidata_id",
            field=models.CharField(
                blank=True,
                help_text="Wikidata QID, e.g. Q180268",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
