# Generated by Django 6.0.2 on 2026-02-23 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_manufacturer_country_manufacturer_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of absolute URLs to images of this award.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AwardRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="Year the award was given (null if unknown).",
                        null=True,
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="catalog.award",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_recipients",
                        to="catalog.person",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("year"), descending=True, nulls_last=True),
                    "award__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("award", "person", "year"),
                        name="catalog_unique_award_recipient",
                    )
                ],
            },
        ),
    ]
