# Generated by Django 6.0.2 on 2026-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_award_awardrecipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="machinemodel",
            name="theme",
        ),
        migrations.AddField(
            model_name="machinemodel",
            name="themes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Resolved theme tags (materialized from relationship claims).",
                related_name="machine_models",
                to="catalog.theme",
            ),
        ),
    ]
