# Generated by Django 6.0.3 on 2026-04-28 20:02

import apps.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_location_catalog_location_unique_slug_per_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=300, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='catalog_location_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(models.F('parent'), django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', False)), name='catalog_location_unique_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('parent__isnull', True)), name='catalog_location_unique_name_at_root'),
        ),
    ]
