# Generated by Django 6.0.3 on 2026-04-28 20:18

import apps.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_location_name_required_and_unique_per_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='creditrole',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='displaysubtype',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='displaytype',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='gameformat',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='gameplayfeature',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='rewardtype',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='technologygeneration',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='technologysubgeneration',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_cabinet_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_cabinet_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='corporateentity',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_corporateentity_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='creditrole',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_creditrole_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='creditrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_creditrole_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='displaysubtype',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_displaysubtype_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='displaysubtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_displaysubtype_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='displaytype',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_displaytype_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='displaytype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_displaytype_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_franchise_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_franchise_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='gameformat',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_gameformat_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='gameformat',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_gameformat_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='gameplayfeature',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_gameplayfeature_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='gameplayfeature',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_gameplayfeature_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_location_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('location_path__regex', '[A-Z]'), _negated=True), name='catalog_location_location_path_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_machinemodel_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_manufacturer_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_manufacturer_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_person_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='rewardtype',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_rewardtype_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='rewardtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_rewardtype_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_series_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_series_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_system_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_system_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_tag_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_tag_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='technologygeneration',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_technologygeneration_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='technologygeneration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_technologygeneration_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='technologysubgeneration',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_technologysubgeneration_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='technologysubgeneration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_technologysubgeneration_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_theme_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='catalog_theme_unique_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '[A-Z]'), _negated=True), name='catalog_title_slug_lowercase'),
        ),
    ]
