# Generated by Django 6.0.2 on 2026-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=10000,
                help_text="Claim priority for conflict resolution. Higher beats lower.",
            ),
        ),
    ]
