# Generated by Django 6.0.3 on 2026-05-13 23:18

import apps.accounts.usernames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[apps.accounts.usernames.validate_username_format]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('username__length__gte', 3)), name='accounts_user_username_min_length'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('username__length__lte', 20)), name='accounts_user_username_max_length'),
        ),
    ]
