# Generated by Django 6.0.3 on 2026-05-05 15:17

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Admin label shown in the kiosk list (e.g. 'Lobby kiosk').", max_length=80, unique=True, validators=[apps.core.validators.validate_no_mojibake])),
                ('page_heading', models.CharField(blank=True, default='', help_text='H1 rendered on the kiosk display. Blank to render no heading.', max_length=60, validators=[apps.core.validators.validate_no_mojibake])),
                ('idle_seconds', models.PositiveIntegerField(default=180, help_text='Idle timeout before redirecting back to /kiosk.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KioskConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hook', models.CharField(blank=True, help_text='Optional short caption shown alongside the title.', max_length=80, validators=[apps.core.validators.validate_no_mojibake])),
                ('position', models.PositiveIntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kiosk.kioskconfig')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.title')),
            ],
            options={
                'ordering': ['config_id', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='kioskconfig',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='kiosk_kioskconfig_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='kioskconfig',
            constraint=models.CheckConstraint(condition=models.Q(('idle_seconds__gte', 10), ('idle_seconds__lte', 3600)), name='kiosk_kioskconfig_idle_seconds_range'),
        ),
        migrations.AddConstraint(
            model_name='kioskconfigitem',
            constraint=models.UniqueConstraint(fields=('config', 'position'), name='kiosk_kioskconfigitem_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='kioskconfigitem',
            constraint=models.UniqueConstraint(fields=('config', 'title'), name='kiosk_kioskconfigitem_title_unique'),
        ),
    ]
