# Generated by Django 6.0.3 on 2026-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskconfig',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='kioskconfig',
            name='kiosk_kioskconfig_name_not_blank',
        ),
        migrations.RemoveField(
            model_name='kioskconfig',
            name='name',
        ),
    ]
