# Generated by Django 6.0.3 on 2026-05-05 22:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_kioskconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kioskconfig',
            name='kiosk_kioskconfig_idle_seconds_range',
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='idle_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Idle timeout before redirecting back to /kiosk.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='kioskconfig',
            constraint=models.CheckConstraint(condition=models.Q(('idle_seconds__gte', 1)), name='kiosk_kioskconfig_idle_seconds_range'),
        ),
    ]
