# Generated by Django 6.0.2 on 2026-02-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opdb_id",
                    models.CharField(
                        help_text='OPDB group identifier, e.g., "G5pe4"',
                        max_length=50,
                        unique=True,
                        verbose_name="OPDB group ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text='Common abbreviation, e.g., "MM" for Medieval Madness',
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text='Brand name if different (e.g., "Bally" for Midway Manufacturing)',
                        max_length=200,
                    ),
                ),
                (
                    "opdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="OPDB's manufacturer_id for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("book", "Book"),
                            ("editorial", "Editorial"),
                            ("other", "Other"),
                        ],
                        default="database",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher priority wins when claims conflict.",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="MachineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ipdb_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="IPDB ID"
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB ID",
                    ),
                ),
                (
                    "pinside_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Pinside ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "machine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "Pure Mechanical"),
                            ("EM", "Electromechanical"),
                            ("SS", "Solid State"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reels", "Score Reels"),
                            ("lights", "Backglass Lights"),
                            ("alpha", "Alpha-Numeric"),
                            ("dmd", "Dot Matrix Display"),
                            ("cga", "CGA (Color Graphics)"),
                            ("lcd", "LCD Screen"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "player_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("theme", models.CharField(blank=True, max_length=300)),
                ("production_quantity", models.CharField(blank=True, max_length=100)),
                (
                    "mpu",
                    models.CharField(
                        blank=True,
                        help_text="Electronic system",
                        max_length=200,
                        verbose_name="MPU",
                    ),
                ),
                (
                    "flipper_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pinside_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("educational_text", models.TextField(blank=True)),
                ("sources_notes", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "alias_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent machine model if this is a cosmetic/LE variant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="machines.machinemodel",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Franchise/title grouping (resolved from claims).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_models",
                        to="machines.machinegroup",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="machines.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturerEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                        max_length=300,
                    ),
                ),
                (
                    "ipdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="IPDB's ManufacturerId for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "years_active",
                    models.CharField(
                        blank=True,
                        help_text='Operating period, e.g., "1931-1977"',
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="machines.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "manufacturer entity",
                "verbose_name_plural": "manufacturer entities",
                "ordering": ["manufacturer", "years_active"],
            },
        ),
        migrations.CreateModel(
            name="DesignCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("design", "Design"),
                            ("art", "Art"),
                            ("mechanics", "Mechanics"),
                            ("music", "Music"),
                            ("sound", "Sound"),
                            ("software", "Software"),
                            ("animation", "Dots/Animation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="machines.machinemodel",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="machines.person",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "person__name"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("citation", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="machines.machinemodel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="machines.source",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["manufacturer", "year"], name="machines_ma_manufac_a8c7f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["machine_type", "year"], name="machines_ma_machine_bdf947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machinemodel",
            index=models.Index(
                fields=["display_type"], name="machines_ma_display_3a794e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="designcredit",
            constraint=models.UniqueConstraint(
                fields=("model", "person", "role"),
                name="unique_credit_per_model_person_role",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["model", "field_name"], name="machines_cl_model_i_b9b409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["source", "model"], name="machines_cl_source__b47063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["user", "model"], name="machines_cl_user_id_d71ac1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["field_name", "is_active"],
                name="machines_cl_field_n_ac7fa5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source__isnull", False), ("user__isnull", True)),
                    models.Q(("source__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="claim_source_xor_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("source__isnull", False)),
                fields=("model", "source", "field_name"),
                name="unique_active_claim_per_source_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("user__isnull", False)),
                fields=("model", "user", "field_name"),
                name="unique_active_claim_per_user_field",
            ),
        ),
    ]
