# Generated by Django 6.0.2 on 2026-02-19 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text='Brand name if different (e.g., "Bally" for Midway Manufacturing)',
                        max_length=200,
                    ),
                ),
                (
                    "ipdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="IPDB's ManufacturerId for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "opdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="OPDB's manufacturer_id for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("book", "Book"),
                            ("editorial", "Editorial"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher wins conflicts. Editorial sources should get the highest priority.",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PinballModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "ipdb_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="IPDB ID"
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="OPDB ID",
                    ),
                ),
                (
                    "pinside_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Pinside ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "machine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "Pure Mechanical"),
                            ("EM", "Electromechanical"),
                            ("SS", "Solid State"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reels", "Score Reels"),
                            ("lights", "Backglass Lights"),
                            ("alpha", "Alpha-Numeric"),
                            ("dmd", "Dot Matrix Display"),
                            ("lcd", "LCD Screen"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "player_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("theme", models.CharField(blank=True, max_length=300)),
                ("production_quantity", models.CharField(blank=True, max_length=100)),
                (
                    "mpu",
                    models.CharField(
                        blank=True,
                        help_text="Electronic system",
                        max_length=200,
                        verbose_name="MPU",
                    ),
                ),
                (
                    "flipper_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ipdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "pinside_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("educational_text", models.TextField(blank=True)),
                ("sources_notes", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="machines.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("design", "Design"),
                            ("art", "Art"),
                            ("mechanics", "Mechanics"),
                            ("music", "Music"),
                            ("sound", "Sound"),
                            ("software", "Software"),
                            ("animation", "Dots/Animation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="machines.person",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="machines.pinballmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "person__name"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("citation", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="machines.pinballmodel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="machines.source",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pinballmodel",
            index=models.Index(
                fields=["manufacturer", "year"], name="machines_pi_manufac_4044f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pinballmodel",
            index=models.Index(
                fields=["machine_type", "year"], name="machines_pi_machine_902ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pinballmodel",
            index=models.Index(
                fields=["display_type"], name="machines_pi_display_f2e01e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="designcredit",
            constraint=models.UniqueConstraint(
                fields=("model", "person", "role"),
                name="unique_credit_per_model_person_role",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["model", "field_name"], name="machines_cl_model_i_b9b409_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["source", "model"], name="machines_cl_source__b47063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["field_name", "is_active"],
                name="machines_cl_field_n_ac7fa5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("model", "source", "field_name"),
                name="unique_active_claim_per_source_field",
            ),
        ),
    ]
