# Generated by Django 6.0.2 on 2026-02-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="ipdb_manufacturer_id",
        ),
        migrations.AlterField(
            model_name="pinballmodel",
            name="display_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reels", "Score Reels"),
                    ("lights", "Backglass Lights"),
                    ("alpha", "Alpha-Numeric"),
                    ("dmd", "Dot Matrix Display"),
                    ("cga", "CGA (Color Graphics)"),
                    ("lcd", "LCD Screen"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ManufacturerEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                        max_length=300,
                    ),
                ),
                (
                    "ipdb_manufacturer_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="IPDB's ManufacturerId for cross-referencing",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "years_active",
                    models.CharField(
                        blank=True,
                        help_text='Operating period, e.g., "1931-1977"',
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="machines.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "manufacturer entity",
                "verbose_name_plural": "manufacturer entities",
                "ordering": ["manufacturer", "years_active"],
            },
        ),
    ]
