# Generated by Django 6.0.2 on 2026-02-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0002_add_manufacturer_entity_and_cga_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opdb_id",
                    models.CharField(
                        help_text='OPDB group identifier, e.g., "G5pe4"',
                        max_length=50,
                        unique=True,
                        verbose_name="OPDB group ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        help_text='Common abbreviation, e.g., "MM" for Medieval Madness',
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pinballmodel",
            name="alias_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent machine if this is a cosmetic/LE variant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aliases",
                to="machines.pinballmodel",
            ),
        ),
        migrations.AddField(
            model_name="pinballmodel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Franchise/title grouping (resolved from claims).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="machines.machinegroup",
            ),
        ),
    ]
